# Generated by Django 6.0 on 2025-12-30 05:40

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('user_prompt', models.TextField(verbose_name='User prompt')),
                ('intent', models.CharField(choices=[('READ', 'Read'), ('GENERATE', 'Generate'), ('REVIEW', 'Review'), ('MODIFY', 'Modify'), ('DELETE', 'Delete'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Intent')),
                ('planner_decision', models.JSONField()),
                ('llm_response', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSession',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('last_interaction_at', models.DateTimeField(blank=True, editable=False, verbose_name='Last_interaction_at')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'historical session',
                'verbose_name_plural': 'historical sessions',
                'db_table': '"history"."session_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalToolExecution',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tool_name', models.CharField(max_length=100, verbose_name='Tool name')),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.interaction', verbose_name='Interaction')),
            ],
            options={
                'verbose_name': 'historical tool execution',
                'verbose_name_plural': 'historical tool executions',
                'db_table': '"history"."tool_execution_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('last_interaction_at', models.DateTimeField(auto_now=True, verbose_name='Last_interaction_at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tool_name', models.CharField(max_length=100, verbose_name='Tool name')),
                ('tool_input', models.JSONField()),
                ('description', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='api.interaction', verbose_name='Interaction')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='api.session', verbose_name='Session')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='api.session', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='HistoricalPendingAction',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tool_name', models.CharField(max_length=100, verbose_name='Tool name')),
                ('tool_input', models.JSONField()),
                ('description', models.TextField()),
                ('confirmed', models.BooleanField(default=False)),
                ('executed', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('interaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.interaction', verbose_name='Interaction')),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'historical pending action',
                'verbose_name_plural': 'historical pending actions',
                'db_table': '"history"."pending_action_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInteraction',
            fields=[
                ('id', models.BigIntegerField(blank=True, db_column='id', db_index=True, verbose_name='Id')),
                ('created_at', models.DateTimeField(blank=True, db_column='dt_created_at', editable=False, null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(blank=True, db_column='dt_modified_at', editable=False, null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('user_prompt', models.TextField(verbose_name='User prompt')),
                ('intent', models.CharField(choices=[('READ', 'Read'), ('GENERATE', 'Generate'), ('REVIEW', 'Review'), ('MODIFY', 'Modify'), ('DELETE', 'Delete'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20, verbose_name='Intent')),
                ('planner_decision', models.JSONField()),
                ('llm_response', models.TextField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'historical interaction',
                'verbose_name_plural': 'historical interactions',
                'db_table': '"history"."interaction_history"',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ToolExecution',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='dt_created_at', null=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, db_column='dt_modified_at', null=True, verbose_name='Modified at')),
                ('active', models.BooleanField(db_column='cs_active', default=True, verbose_name='Active')),
                ('tool_name', models.CharField(max_length=100, verbose_name='Tool name')),
                ('input_payload', models.JSONField()),
                ('output_payload', models.JSONField()),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='api.interaction', verbose_name='Interaction')),
            ],
            options={
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user'], name='api_session_user_id_71b875_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['last_interaction_at'], name='api_session_last_in_797049_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['session'], name='api_interac_session_828838_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['intent'], name='api_interac_intent_267c0d_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['created_at'], name='api_interac_dt_crea_0c9813_idx'),
        ),
    ]
