# Generated by Django 6.0 on 2026-01-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsession',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='session',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
